// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function OpenAudioFile() {
  return window['go']['main']['App']['OpenAudioFile']();
}

export function OpenVideoFile() {
  return window['go']['main']['App']['OpenVideoFile']();
}

export function ProcessVideo(arg1) {
  return window['go']['main']['App']['ProcessVideo'](arg1);
}

export function SaveVideoFile(arg1, arg2) {
  return window['go']['main']['App']['SaveVideoFile'](arg1, arg2);
}
