// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function GetVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function InstallFFmpeg():Promise<void>;

export function OpenAudioFile():Promise<string>;

export function OpenVideoFile():Promise<string>;

export function ProcessVideo(arg1:main.ProcessTask):Promise<void>;

export function SaveVideoFile(arg1:string,arg2:string):Promise<string>;
